version: "3.2"

networks:
  internal:
  external:
    driver: bridge

volumes:
  postgres:
  minio:
  mongodb:
  tripnjoy-grafana:

services:
  app:
#    image: gabray/tripnjoy_back:latest
    build: ./
    networks:
      - internal
      - external
    depends_on:
      - db
      - mongo
    ports:
      - "8080:8080"
      - "25570:25570"
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/postgres"
      - "spring.data.mongodb.host=mongo"
      - "spring.profiles.active=${PROFILE:-default}"
      - "spring.boot.admin.client.url=http://admin:8084"
      - "agora.app.id=${AGORA_APP_ID}"
      - "agora.app.certificate${AGORA_APP_CERT}"

  db:
    image: "postgres:13.6"
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./sql/db_tripnjoy.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=postgres"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb
    networks:
      - internal

  minio:
    image: "quay.io/minio/minio"
    networks:
      - external
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=${MINIO_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}"
    volumes:
      - "minio:/data"

  grafana:
    image: "grafana/grafana-oss:latest"
    networks:
      - internal
      - external
    ports:
      - "3001:3000"
    volumes:
      - "tripnjoy-grafana:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"

  prometheus:
    image: "prom/prometheus"
    depends_on:
      - app
    networks:
      - internal
    ports:
      - "9091:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  admin:
    image: "gabray/tripnjoy_admin"
    networks:
      - internal
    ports:
      - "8084:8084"
