version: "3.2"

networks:
  internal:
  external:
    driver: bridge

volumes:
  postgres:

services:
  app:
    build: .
    networks:
      - internal
      - external
    depends_on:
      - db
      - mongo
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/postgres"
      - "spring.data.mongodb.host=mongo"
      - "spring.profiles.active=${PROFILE:-default}"

  db:
    image: "postgres:13.6"
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - internal