global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'app:25570' ]
        labels:
          server: 'app'
  - job_name: 'prom_spring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: '1s'
    static_configs:
      - targets: [ 'app:8080' ]
        labels:
          server: 'spring'
